/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function generateRouteManifestNative(pagesDir: string): Array<RouteRecord>
export declare function renderRouteNative(inputJson: string): string
export declare function resolveRouteNative(path: string, routes: Array<RouteRecord>): RouteState | null
export declare function generateRuntimeRouterNative(): string
export const enum SegmentType {
  Static = 0,
  Dynamic = 1,
  CatchAll = 2,
  OptionalCatchAll = 3
}
export interface ParsedSegment {
  segmentType: SegmentType
  paramName?: string
  raw: string
}
export interface RouteRecord {
  path: string
  regex: string
  paramNames: Array<string>
  score: number
  filePath: string
}
export interface RouteState {
  path: string
  params: Record<string, string>
  query: Record<string, string>
  matched?: RouteRecord
}
export interface RouteManifest {
  routes: Array<RouteRecord>
  generatedAt: number
}
export declare function routerBridge(): string
